#!/bin/bash

mkdir -p /tmp/rom # Where to sync source
cd /tmp/rom

# Repo init command, that -device,-mips,-darwin,-notdefault part will save you more time and storage to sync, add more according to your rom and choice. Optimization is welcomed! Let's make it quit, and with depth=1 so that no unnecessary things.
repo init -q --no-repo-verify --depth=1 -u git://github.com/project-legionos/manifest.git -b 11 -g default,-device,-mips,-darwin,-notdefault

# Sync source with -q, no need unnecessary messages, you can remove -q if want! try with -j30 first, if fails, it will try again with -j8
repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j 30 || repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j 8

git clone https://github.com/legionos-devices/device_xiaomi_miatoll.git -b 11 device/xiaomi/miatoll

git clone https://github.com/legionos-devices/device_xiaomi_sm6250-common.git -b 11 device/xiaomi/sm6250-common

git clone --depth=1 https://github.com/legionos-devices/vendor_xiaomi_miatoll.git vendor/xiaomi/miatoll

git clone --depth=1 https://github.com/legionos-devices/vendor_xiaomi_sm6250-common.git vendor/xiaomi/sm6250-common

git clone --depth=1 https://github.com/legionos-devices/kernel_xiaomi_sm6250.git kernel/xiaomi/sm6250

cd /tmp/
sudo apt-get install git-core -y
sudo apt-get update
sudo apt-get install openjdk-8-jdk -y
sudo apt-get install openjdk-8-jre -y
sudo apt-get install git-core python gnupg flex bison gperf build-essential zip curl gcc-multilib g++-multilib libc6-dev-i386  ccache libgl1-mesa-dev lib32ncurses5-dev \ unzip libesd0-dev squashfs-tools -y
sudo apt-get update && sudo apt-get install bc git-core gnupg flex bison gperf squashfs-tools build-essential zip curl libncurses5-dev openjdk-8-jre openjdk-8-jdk pngcrush schedtool libxml2 libxml2-utils xsltproc lzop libc6-dev schedtool g++-multilib lib32ncurses5-dev gcc-multilib maven tmux screen w3m ncftp -y
sudo apt-get install git-core gnupg flex bison gpe rf build-essential zip curl zlib1g-dev gcc-multilib g++-multilib libc6-dev-i386 lib32ncurses5-dev x11proto-core-dev libx11-dev lib32z-dev ccache libgl1-mesa-dev libxml2-utils xsltproc unzip curl flex git liblz4-tool libncurses5-dev libsdl1.2-dev libwxgtk3.0-dev maven pngcrush schedtool squashfs-tools xsltproc zip zlib1g-dev g++-multilib gcc-multilib wput -y
sudo apt-get install wget -y
curl https://storage.googleapis.com/git-repo-downloads/repo > repo
chmod a+x repo
sudo install repo /usr/local/bin
rm repo
sudo apt-get upgrade -y
cd /tmp/rom/
